### ISSUE TITLE
(S)CSS File Organization

### ISSUE THREAD

**Issue by smithtimmytim** [acl-services/code-styleguide#4]
The current organazation of CSS in most of our projects at the moment isn't great. In Results thankfully, CSS is mostly organized by model. So all styles for surveys will you usually be in `_surveys.scss`. I still think there's a better way to do this.

I think the [SMACSS methodology for organizing CSS files is pretty great](https://smacss.com/book/categorizing). And even app by app, there are styles that shouldn't live in a stylesheet particular to a model because it can be used anywhere.

**Comment by johnpeele** [comment]
@smithtimmytim so glad you are thinking about this. It has been driving me crazy lately trying to locate styles in the projects that I work on.

I have actually been thinking about it myself while working on my draft of the ACL Design System writeup - https://paper.dropbox.com/doc/DRAFT-Proposal-for-ACL-Design-System-mDamvxhgxjKQnoywwsjjj#:h2=ACL-UI-Kit---“Proposed”-Organi  - And I would say that my proposal shares a lot with the SMACSS methodology.

Jayde and myself have also mentioned Harry Roberts' (CSS Wizardry) ITCSS (Inverted Triangle CSS) approach

![image](https://cloud.githubusercontent.com/assets/84169/17364695/b5735d3e-594f-11e6-8ef4-024e2835f024.png)

I honestly think that ITCSS is a tad overcomplicated 😉 

Then, regardless of which approach we ultimately adopt or create for ourselves, I think that the convention of using prefixes to help everyone quickly identify styles is a must:

- `.l-` for layout
- `.c-` or `.m-` for components/modules
- `.is-` AND `.has-` for state  (`.is-hidden`  `.has-loaded`)
- etc etc

Those are some of my thoughts for now 😄

**Comment by jayde-acl** [comment]
I really like the way that ITCSS sets things up, I think it's a bit complicated to wrap your head around initially BUT we work on a very complicated platform. I had to read it several times and rewatch the videos but I love how it ties very nicely into BEM, OOCSS, etc, etc.

But! I'm happy with either approach too, I definitely think we're headed on the right path.

**Comment by pxsmith** [comment]
Have you guys seen SUIT? It’s similar to these other.. er.. theories(?), but maybe there’s something we like and can steal from it. https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md

**Comment by johnpeele** [comment]
Where do we stand on this?  Any new thoughts?

I am still strong on this approach:
- `.l-` for layout
- `.c-` or `.m-` for components/modules
- `.u-` for utilities
- `.is-` AND `.has-` for state  (`.is-hidden`  `.has-loaded`)

I think the SUIT approach introduces too much capitalization, which is yet another level of naming structure we have to remember. KISS.

**Comment by smithtimmytim** [comment]
I really like this idea John. We also decided on using `.f-` for QA functional tests. Classes with `.f` wouldn't have any styling attached to them whatsoever. Write something up and open a PR @johnpeele.

**Comment by mattcrest** [comment]
I have very little knowledge on this and really do not have a strong opinion, but would `.qa-` make it more obvious/intuitive for non-styling/functional tests?
